export default {

  CLEAR_ALL: 'CLEAR_ALL',
  DELETE_ITEM: 'DELETE_ITEM',
  // 登陆
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  // 注册
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',

  // 登陆
  FORGET_REQUEST: 'FORGET_REQUEST',
  FORGET_SUCCESS: 'FORGET_SUCCESS',
  FORGET_FAILURE: 'FORGET_FAILURE',


}

